// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hearjlibntcenblbanzz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhlYXJqbGlibnRjZW5ibGJhbnp6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEwOTkzMzIsImV4cCI6MjA1NjY3NTMzMn0.fyTGMrzKOk1Dh49Fw6RJFnhaokZ-syniuabONa1GkdE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);