// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hearjlibntcenblbanzz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhlYXJqbGlibnRjZW5ibGJhbnp6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEwOTkzMzIsImV4cCI6MjA1NjY3NTMzMn0.fyTGMrzKOk1Dh49Fw6RJFnhaokZ-syniuabONa1GkdE";

const supabaseUrlDev = "https://uvikvmwodlewbplxecnb.supabase.co";
const supabaseAnonKeyDev = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV2aWt2bXdvZGxld2JwbHhlY25iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxODc4OTksImV4cCI6MjA1OTc2Mzg5OX0.to7yZPGZdGbtn-GQlVSBVSzoeYTJcY5gtCMwlcFC1cA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = createClient<Database>(supabaseUrlDev, supabaseAnonKeyDev);

//export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);