// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pzrejiqbbkirxiitsche.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB6cmVqaXFiYmtpcnhpaXRzY2hlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5ODAzMDksImV4cCI6MjA2MDU1NjMwOX0.rY2wcUKwp1EDRpBYOfewhyVLWZlzY9w0VklADGdwuDM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);